# Use root/example as user/password credentials
version: '3.6'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '80:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  dbdata:
